project_name: mvm

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/mvm
      main: ./main.go
      ldflags:
        - -s -w -X github.com/craiggwilson/mvm/cmd.binaryVersion={{.Version}} -X github.com/craiggwilson/mvm/cmd.versionDate={{time "2006-01-02"}}
        - -X github.com/craiggwilson/mvm/cmd.gitVersion={{.Commit}}
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
